// <auto-generated />
namespace npl_referralTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addservicestoclients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addservicestoclients));
        
        string IMigrationMetadata.Id
        {
            get { return "201610141656062_add-services-to-clients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
